apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: datadog
spec:
  template:
    spec:
      containers:
      - image: 'asia-northeast1-docker.pkg.dev/sre-practice-392013/dev/datadog:COMMIT_SHA'
        ports:
          - containerPort: 8000
        env:
          - name: SUPABASE_PUBLIC_API_KEY
            valueFrom:
              secretKeyRef:
                key: '1'
                name: SUPABASE_PUBLIC_API_KEY
      serviceAccountName: cloudrun@meshi-393314.iam.gserviceaccount.com