apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: meshi-api
spec:
  template:
    spec:
      serviceAccountName: cloudrun@meshi-393314.iam.gserviceaccount.com
      containers:
      - image: 'asia-northeast1-docker.pkg.dev/meshi-393314/dev/meshi-api:$COMMIT_SHA'
        ports:
          - containerPort: 8000
        env:
          - name: SUPABASE_PUBLIC_API_KEY
            valueFrom:
              secretKeyRef:
                key: '1'
                name: SUPABASE_PUBLIC_API_KEY